# Generated by Django 6.0.1 on 2026-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charvariety',
            name='description',
            field=models.TextField(default='empty'),
        ),
    ]
