# Generated by Django 6.0.1 on 2026-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_charvariety_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chai_varieties', models.ManyToManyField(related_name='stores', to='pages.charvariety')),
            ],
        ),
    ]
